steps:
- id: "descriptografando chave"
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - kms
    - decrypt
    - --ciphertext-file=./backend/storage/credentials/google/service-account-storage.json.enc
    - --plaintext-file=./backend/storage/credentials/google/service-account-storage.json
    - --location=global
    - --keyring=testing-lesson
    - --key=service-account

- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
  env:
    - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
    - GOOGLE_CLOUD_KEY_FILE=service-account-storage.json
    - GOOGLE_CLOUD_STORAGE_BUCKET=balbi-code-micro-videos
    - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/balbi-code-micro-videos
    - TESTING_PROD=true

- id: "Chown in /var/www"
  name: 'docker'
  args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

- id: "composer version"
  name: 'docker'
  args: ['exec', '-t', 'app' ,'composer', '--version']

- id: "Rodando composer"
  name: 'docker'
  args: ['exec', '-t', 'app' ,'composer', 'install']

- id: "Copiando .env"
  name: 'docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- id: "Copiando .env.testing"
  name: 'docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example.testing', '.env.testing']

- id: "rodando key:generate"
  name: 'docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/backend/artisan', 'key:generate']

- id: "rodando migrations"
  name: 'docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/backend/artisan', 'migrate']

- id: "rodando phpunit"
  name: 'docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/backend/vendor/bin/phpunit', '-c', '/var/www/backend/phpunit.xml']
